eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
  instance:
    hostname: localhost
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 10000
microservice:
  endpoints:
    endpoint:
      uri: /forex/currency-exchange/from/{from}/to/{to}
test:
  value: friri1 
