eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservice:
  endpoints:
    endpoint:
      uri: /forex/currency-exchange/from/{from}/to/{to}
test:
  value: friri
